import math

def generate_weekly_plan(roadmap_result: dict, hours_per_week: int, plan_type: str = "Standard") -> dict:
    """
    Transforms a roadmap object into chronological weekly blocks.
    
    plan_type: "Standard" (auto-calculate based on hours), "2-Week Crash Course", "4-Week Plan", "Weekend Warrior"
    """
    roadmap = roadmap_result.get("roadmap", [])
    if not roadmap:
        return {}
        
    weeks = []
    current_week = []
    current_week_hours = 0
    week_limit = hours_per_week
    
    # Override logic based on plan type
    if plan_type == "2-Week Crash Course":
        # Force the entire roadmap into 2 weeks
        total_hours = sum([stg["course"]["estimated_duration_hours"] for stg in roadmap if stg.get("course")])
        week_limit = max(total_hours / 2, hours_per_week)
    elif plan_type == "4-Week Plan":
        total_hours = sum([stg["course"]["estimated_duration_hours"] for stg in roadmap if stg.get("course")])
        week_limit = max(total_hours / 4, hours_per_week)
        
    for stage in roadmap:
        course = stage.get("course")
        dur = course["estimated_duration_hours"] if course else 2.0 # Assume 2 hours for theory
        
        # If adding this stage goes over the limit AND we already have items in the week, push to next
        if current_week_hours + dur > week_limit and len(current_week) > 0:
            weeks.append({
                "week": len(weeks) + 1,
                "items": current_week,
                "total_hours": current_week_hours
            })
            current_week = []
            current_week_hours = 0
            
        current_week.append(stage)
        current_week_hours += dur
        
    if current_week:
        weeks.append({
            "week": len(weeks) + 1,
            "items": current_week,
            "total_hours": current_week_hours
        })
        
    return {
        "plan_type": plan_type,
        "target_node": roadmap_result.get("target_node"),
        "weeks": weeks,
        "total_weeks": len(weeks),
        "total_hours_scheduled": sum(w["total_hours"] for w in weeks)
    }

def format_plan_as_text(plan: dict) -> str:
    """Format the generated plan into a downloadable markdown/text string."""
    out = []
    target = plan.get("target_node")
    title = target.title if target else "Custom Study Plan"
    
    out.append(f"# {plan.get('plan_type')} Plan: Mastering {title}")
    out.append(f"Total Duration: ~{plan.get('total_hours_scheduled'):.1f} hours across {plan.get('total_weeks')} weeks.\n")
    out.append("---")
    
    for week in plan.get("weeks", []):
        out.append(f"\n## Week {week['week']} (approx. {week['total_hours']:.1f} hours)")
        for item in week["items"]:
            node = item["node"]
            c = item["course"]
            c_name = c["title"] if c else "Conceptual Theory"
            dur = c["estimated_duration_hours"] if c else 2.0
            out.append(f" - [ ] {node.title} -> {c_name} ({dur}h)")
            
    out.append("\n\n*Generated by CourseCompass Adaptive Learning Engine*")
    return "\n".join(out)
